### ISSUE TITLE
split into front-end/back-end

### ISSUE THREAD

**Issue by proph8** [nightmareinc/js-best-practices#2]
Hey,
I guess it would be a good idea to make this project about everything in JS!
front-end samples and practices for new frameworks
and back-end practices like Node.js

**Comment by nightmareinc** [comment]
hey, 
that is my final goal, to bring together a package for newcomers to JavaScript that guides and trains them from the very core to working full-stack with various frameworks and stacks, but for the time being i am focusing on JavaScript core features and techniques.
